### ISSUE TITLE
CAn't post new posts

### ISSUE THREAD

**Issue by StevenEdelmann** [StevenEdelmann/secondProject#2]
When I run my code in the browser, when I submit a new post, it says "Cannot read property 'poster' of undefined", but I am just telling it to assign a new value into the posts table. I think it's on line 83 of app.js

**Comment by andrewfritz86** [comment]
Looking now. Any updates?

**Comment by andrewfritz86** [comment]
Looks like req.body is undefined

**Comment by andrewfritz86** [comment]
Issue is with the config of your middleware (pain in the ass)
add this to your server

`app.use(bodyparser.urlencoded({ extended: true }));`

also, restructure your form a bit. should look like

```
<form method="POST" action="/posts">
put your name
<input type="text" name="username">
put your comment
<input type="text" name="comment">
</form>

```

Also, use the route '/posts' in order to be RESTful.
